# Reusable workflow to run the following jobs:
#
#   - multiplatform-tests
#     - [ windows-2019 | windows-2022 ]
#     - [ Debug | Release ]
#     - execute tests in different versions of ubuntu with different build types
#

name: windows-ci

on:

  workflow_call:
    inputs:

      dependencies_artifact_postfix:
        description: >
          Postfix name to add to artifact name to download dependencies.
          This is use to download a specific artifact version from eProsima-CI.
        required: true
        default: '_nightly'
        type: string

      ref:
        description: >
          The branch or tag name to checkout.
        required: true
        type: string
        default: 'main'

env:
  code_packages_names: 'ddsenabler ddsenabler_yaml ddsenabler_participants'
  docs_packages_names: 'docs'

jobs:

#####################################################################
# TEST

  multiplatform-tests:
    name: ${{ matrix.os }}-ci
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - windows-2022
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      os: ${{ matrix.os }}
      dependencies_artifact_postfix: ${{ inputs.dependencies_artifact_postfix || '_nightly' }}
      ref: ${{ inputs.ref }}
    secrets: inherit
